name: Update Stats
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch stats
        run: |
          gh repo view $GITHUB_REPO --json stargazerCount,forkCount,openGraphImageUrl --jq '{stars:.stargazerCount,forks:.forkCount}' > stats.json
          echo "# Stats" > STATS.md
          cat stats.json >> STATS.md
      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add STATS.md || true
          git commit -m "ci: update STATS.md [skip ci]" || true
          git push || true
